name: ai_clients
description: A Dart package providing a unified interface for interacting with various AI models through different clients.
repository: https://github.com/mjablecnik/ai_clients
tags: [ai, llm, client, openai, baseten, together]
version: 0.5.0

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.8.0+1
  mcp_client: ^1.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
